stages:
  - deps
  - build
  - lint
  - test
  - e2e
  - release
  - docker

variables:
  DOCKER_ORG: aanand91119
  DOCKER_SERVER: semaphore
  DOCKER_RUNNER: runner
  SWAGGER_VERSION: v0.30.5
  GORELEASER_VERSION: v1.25.1
  GOLINTER_VERSION: v1.57.2

before_script:
  - apt update -y
  - apt install -y curl npm golang

deps:tools:
  stage: deps
  script:
    - go install github.com/goreleaser/goreleaser@$GORELEASER_VERSION

deps:be:
  stage: deps
  script:
    - go mod vendor

deps:fe:
  stage: deps
  script:
    - cd web && npm install

build:fe:
  stage: build
  script:
    - cd web && npm run build
  artifacts:
    paths:
      - api/public/

build:be:
  stage: build
  script:
    - env CGO_ENABLED=0 GOOS=$GOOS GOARCH=$GOARCH go build -o bin/semaphore -tags "netgo" -ldflags "-s -w -X github.com/ansible-semaphore/semaphore/util.Ver=$VERSION -X github.com/ansible-semaphore/semaphore/util.Commit=$SHA -X github.com/ansible-semaphore/semaphore/util.Date=$DATE" ./cli
  variables:
    TAG: $(git name-rev --name-only --tags --no-undefined HEAD 2>/dev/null || git rev-parse --abbrev-ref HEAD)
    SHA: $(git log --pretty=format:'%h' -n 1)
    VERSION: $CI_COMMIT_REF_NAME
    DATE: $(date +%s)

lint:fe:
  stage: lint
  script:
    - cd web && npm run lint

test:fe:
  stage: test
  script:
    - cd web && npm run test:unit

test:be:
  stage: test
  script:
    - go test -v -coverprofile=coverage.out ./...

e2e:deps:
  stage: e2e
  script:
    - cd web && npm install dredd@13.1.2

e2e:test:
  stage: e2e
  script:
    - ./web/node_modules/.bin/dredd --config .dredd/dredd.testing.yml

docker:build:
  stage: docker
  before_script:
    - |
      echo $DOCKER_REGISTRY_PASSWORD | docker login -u $DOCKER_REGISTRY_USER --password-stdin $DOCKER_REGISTRY
  script:
    - docker build -f deployment/docker/server/Dockerfile -t $DOCKER_ORG/$DOCKER_SERVER:$CI_COMMIT_TAG .
    - docker build -f deployment/docker/runner/Dockerfile -t $DOCKER_ORG/$DOCKER_RUNNER:$CI_COMMIT_TAG .
  rules:
    - if: $CI_COMMIT_TAG

docker:push:
  stage: docker
  script:
    - docker push $DOCKER_ORG/$DOCKER_SERVER:$CI_COMMIT_TAG
    - docker push $DOCKER_ORG/$DOCKER_RUNNER:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG